#Le volumes n'étant pas sur un NAS il faut qu'il soit présent sur l'hote.
version: '2'
services:
  bind:
    container_name: dns_server
    restart: always
    image: sameersbn/bind:9.9.5-20161106
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "10000:10000/tcp"
    volumes:
      - dns-data:/data
    environment:
      - ROOT_PASSWORD=l9o8i7c6k5

volumes:
  dns-data:
